---
sidebar: sidebar
permalink: ai-workloads-overview.html
keywords: overview, concepts, features, use case, workloads, AI, Bedrock, knowledgebase
summary: Workload Factory for AI workloads enables you to integrate Amazon FSx for NetApp ONTAP file systems with your MLOps platforms and GenAI foundation models. This provides you with high performance storage with a rich set of protection, security, and cost optimization features for your AI datasets.
---

= Learn about Workload Factory for AI workloads
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory for AI workloads enables you to integrate Amazon FSx for NetApp ONTAP file systems with your MLOps platforms and GenAI foundation models. This provides you with high performance storage with a rich set of protection, security, and cost optimization features for your AI datasets.

Developing a chatbot that is tailored to your organization's data enables you to leverage your own knowledge and expertise. This customization capability ensures accurate and relevant responses to organization-specific questions, enhancing the satisfaction and productivity for all of your users.

== Benefits of using the AI workloads capability to create your chatbot

A chatbot simulates human conversation through voice commands or text chats, or both. It is an artificial intelligence (AI) feature that can be embedded and used through any major messaging application. Building your chatbot using Workload Factory provides the following features:

* Ability to embed your organization's unstructured data into an enterprise chatbot application. 

* Seamlessly integrate customer databases, knowledge bases, and more to provide real-time responses with your organization knowledge.

* Preserve user permissions in files embedded in the chatbot to ensure that data security and privacy is maintained. The chatbot provides answers based on those permissions so that only authorized users receive responses from protected files when using the chatbot.

* Provide a secure deployment within your customer account where your organizational data is never externally exposed.

== How Workload Factory helps to build your chatbot

Workload Factory helps to build your chatbot in the following ways:

* Leverage your FSx for ONTAP file systems for storing your organizations chatbot data sources.

* Build the chatbot and conversation starters so you can test the chatbot locally.

* Perform the actual deployment; including the NetApp AI Engine instance and internal databases.

* Connect the AI Engine instance with your FSx for ONTAP system and Amazon Bedrock.

== How the AI chatbot capability works

The AI chatbot uses your organizations internal information to complement data available on the internet to provide customized answers to questions asked by your users in your organization.

== Cost

There is no cost for using the AI chatbot capability of Workload Factory.

You'll need to pay for AWS resources that you deploy in support of the chatbot. For example, you will pay AWS for the Amazon Bedrock AI service, FSx for ONTAP file system and storage capacity, and the AI engine instance.

== Licensing

No special licenses are needed from NetApp to use the AI capabilities of Workload Factory.
