---
sidebar: sidebar
permalink: ai-workloads-overview.html
keywords: overview, concepts, features, use case, workloads, how workload factory works
summary: Workload Factory for AI workloads enables you to integrate Amazon FSx for NetApp ONTAP file systems with your MLOps platforms and GenAI foundation models. This provides you with high performance storage with a rich set of protection, security, and cost optimization features.
---

= Learn about Workload Factory for AI workloads
:icons: font
:imagesdir: ./media/

[.lead]
Workload Factory for AI workloads enables you to integrate Amazon FSx for NetApp ONTAP file systems with your MLOps platforms and GenAI foundation models. This provides you with high performance storage with a rich set of protection, security, and cost optimization features.

== Benefits of using the AI workloads capability to create your chatbot

A chatbot simulates human conversation through voice commands or text chats or both. It is an artificial intelligence (AI) feature that can be embedded and used through any major messaging application. Building your chatbot using Workload Factory provides the following features:

* Ability to embed your organization's unstructured data into an enterprise chatbot application. 
* Seamlessly integrate customer databases, knowledge bases, and more to provide real-time responses with your organization knowledge.
* Preserve user permissions in files embedded in the chatbot to ensure that data security and privacy is maintained. The chatbot provides answers based on those permissions so that only authorized users receive responses from protected when using the chatbot.
* Provide a secure deployment within your customer account where your organizational data is never exposed externally.

== How Workload Factory helps to build your chatbot

Workload Factory helps to build your chatbot in the following ways:

* Leverage your FSx for ONTAP file systems for storing your organizations chatbot sources and the AI Engine databases.
* Perform the actual deployment

== How the VMware Cloud on AWS onboarding advisor works

The onboarding advisor can help you move on-premises virtual machines (VMs) and their data, running on any VMware supported datastores, to VMware Cloud datastores, which includes supplemental NFS datastores on FSx for ONTAP file systems.

== Cost

There is no cost for using the VMware Cloud on AWS onboarding advisor.

You'll need to pay for AWS resources that you deploy based on the recommendations from the onboarding advisor.

== Licensing

No special licenses are needed from NetApp to use the onboarding advisor.
