---
sidebar: sidebar
permalink: aws-requirements.html
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites, requirements
summary: There are certain AWS resources and requirements that you'll need before you begin to build your knowledge base. This includes having your AWS log in credentials, a deployed FSx for ONTAP file system that contains the data sources you want to integrate in your knowledge base, access to the Amazon Bedrock AI service, and more.
---

= AWS requirements
:icons: font
:imagesdir: ./media/

[.lead]
There are certain AWS resources and requirements that you'll need before you begin to build your knowledge base. This includes having your AWS log in credentials, a deployed FSx for ONTAP file system that contains the data sources you want to integrate in your knowledge base, access to the Amazon Bedrock AI service, and more.
 
AWS credentials::
You'll need your AWS credential whether you plan to have Workload Factory deploy and manage AWS resources, or whether you plan to log in to AWS and use the CLI or CloudFormation to manage AWS resources.

AWS permissions and user::
If you plan to use CloudFormation to automate any of your deployment processes, you'll need a user with a role that has the appropriate permissions to run CloudFormation.

Amazon Bedrock service subscription::
Amazon Bedrock enables you to use foundation models and it provides the capabilities to build generative AI applications. You'll need an AWS Identity and Access Management (IAM) role that provides Amazon Bedrock permission to access other AWS resources and services. https://aws.amazon.com/bedrock/[Learn more about Amazon Bedrock].

FSx for ONTAP file system::
* This file system contains the data sources that you'll be integrating into your knowledge base. 
* It also needs to have enough free capacity so that the database that stores the data generated by the foundational model can be saved to a new volume.
* You'll need to know the AWS region, VPC, and Subnet where the AWS FSx for ONTAP system resides.
* You'll need to know the tag key/value pairs that you want to apply to the AWS resources that are part of this deployment (optional).
* You'll need to know the Key pair information that allows you to securely connect to the NetApp AI engine instance.
