---
sidebar: sidebar
permalink: aws-requirements.html
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites, requirements
summary: There are certain AWS resources and requirements that you'll need before you begin to build your knowledge base. This includes having your AWS log in credentials, a deployed FSx for ONTAP file system that contains the data sources you want to integrate in your knowledge base, access to the Amazon Bedrock AI service, and more.
---

= AWS requirements
:icons: font
:imagesdir: ./media/

[.lead]
There are certain AWS resources and requirements that you'll need before you begin to build your knowledge base. This includes having your AWS login credentials, a deployed FSx for ONTAP file system that contains the data sources you want to integrate in your knowledge base, access to the Amazon Bedrock AI service, and more.
 
AWS credentials::
You'll need your AWS credentials so that Workload Factory can deploy and manage AWS resources.
//, or whether you plan to log in to AWS and use the CLI or CloudFormation to manage AWS resources.

//AWS permissions and user::
//If you plan to use CloudFormation to automate any of your deployment processes, you'll need a user with a role that has the appropriate permissions to run CloudFormation.

Amazon Bedrock service::
Amazon Bedrock enables you to use foundation models and it provides the capabilities to build generative AI applications. You'll need an AWS Identity and Access Management (IAM) role that provides Amazon Bedrock permission to access other AWS resources and services. 
+
https://aws.amazon.com/bedrock/[Learn more about Amazon Bedrock].

Chat model::
You must enable the foundational chat model that you plan to use before creating your knowledge base. 
+
https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html[See the list of supported foundational models].
+
You can link:manage-knowledgebase.html#evaluate-chat-models-before-creating-a-knowledge-base[evaluate chat models] before creating a knowledge base to see which model is best for your requirements.

FSx for ONTAP file system::
You'll need to deploy and discover a minimum of one FSx for ONTAP file system:
+
* One file system will be used by the NetApp GenAI engine to store the vector database used by the knowledge base. 
+
This FSx for ONTAP file system must use FlexVol volumes. FlexGroup volumes are not supported.
* One or more file systems will contain the data sources that you'll be integrating into your knowledge base. 
+
One FSx for ONTAP file system can be used for both of these purposes, or you can use multiple FSx for ONTAP file systems.

* You'll need to know the AWS region, VPC, and subnet where the AWS FSx for ONTAP file system resides.
* You'll need to know the tag key/value pairs that you want to apply to the AWS resources that are part of this deployment (optional).
* You'll need to know the key pair information that allows you to securely connect to the NetApp AI engine instance.
