---
sidebar: sidebar
permalink: create-knowledgebase.html
keywords: ai, chatbot, creating, knowledge base
summary: After you've deployed the AI infrastructure and identified the data sources that you'll integrate in your knowledge base from your FSx for ONTAP datastores, you are ready to build the knowledge base using workload factory. As part of this step you'll also define the AI characteristics and create conversation starters.
---

= Create a GenAI knowledge base
:icons: font
:imagesdir: ./media/

[.lead]
After you've deployed the AI infrastructure and identified the data sources that you'll integrate in your knowledge base from your FSx for ONTAP datastores, you are ready to build the knowledge base using workload factory. As part of this step, you'll also define the AI characteristics and create conversation starters.

.About this task
Knowledge bases have two data integration modalities - _public mode_ and _Enterprise mode_. 

Public mode:: A knowledge base can be used without integrating data sources from your organization. In this case, an application integrated with the knowledge base will only provide results from publicly available information on the internet. This is known as a _public mode_ integration.

Enterprise mode:: In most cases you'll want to integrate data sources from your organization into the knowledge base. This is known as an _Enterprise mode_ integration because it provides knowledge from your enterprise.
+
Data sources from your organization may contain Private Identity Information (PII). To safeguard this sensitive information, you can enable _data guardrails_ when creating and configuring knowledge bases. Data guardrails, powered by BlueXP classification, identifies and masks PII, making it inaccessible and irretrievable.
+
link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html[Learn about BlueXP classification^].
+
NOTE: BlueXP workload factory for GenAI does not mask sensitive personal information (SPii). Refer to link:https://docs.netapp.com/us-en/bluexp-classification/reference-private-data-categories.html#types-of-sensitive-personal-data[Types of sensitive personal data^] for more information about this type of data.
+
NOTE: Data guardrails can be enabled or disabled at any time. If you switch data guardrails enablement, Workload Factory scans the entire knowledge base from scratch, which incurs a cost.  

== Create and configure the knowledge base

The knowledge base defines characteristics such as the Bedrock AI models and embedding format that you want to use to create your knowledge base.

.Steps

. Log in to workload factory using one of the link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html[console experiences^].

. In the AI workloads tile, select *Deploy & manage*. 

. From the Knowledge bases tab, select *Add knowledge base*.

. On the Define knowledge base page, configure the knowledge base settings:

.. *Name*: Enter the name you want to use for the knowledge base.
.. *Description*: Enter a detailed description for the knowledge base.
.. *Embedding model*: The embedding model defines how your data will be converted into vector embeddings for the knowledge base. Workload factory supports the following models:
+
* Titan Embeddings G1 - Text
* Titan Embedding Text v2
* Titan Multimodal Embeddings G1
+
Note that you must have already enabled the embedding model from Amazon Bedrock.
+
https://aws.amazon.com/bedrock/titan/[Learn more about Amazon Titan^]

.. *Chat model*: Choose from Claude chat models that are integrated in Amazon Bedrock. Note that you must have already enabled the chat model from Amazon Bedrock.
+
Learn more about the available models to help make your selection: https://aws.amazon.com/bedrock/claude/[Anthropic's Claude in Amazon Bedrock^]
.. *Data guardrails*: Choose whether you want to enable or disable data guardrails. link:https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html[Learn about data guardrails, powered by BlueXP classification^].
+
The following prerequisites must be complete to enable data guardrails. 
+
* A service account is required to communicate with BlueXP classification. You must have the _Organization admin_ role on your BlueXP tenancy account for service account creation. A member who has the Organization admin role can complete all actions in BlueXP. link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#add-a-role-to-a-member[Learn how to add a role to a member in BlueXP^]
+
* The AI engine must have access to the BlueXP API endpoint: \https://api.bluexp.netapp.com.
+ 
* You'll need to do the following as described in link:https://docs.netapp.com/us-en/bluexp-classification/task-deploy-cloud-compliance.html#quick-start[BlueXP classification documentation^]: 
+
1. Create a BlueXP Connector
2. Ensure that your environment can meet the prerequisites
3. Deploy BlueXP classification 

.. *Conversation starters*: Choose whether you want to provide up to four conversation starter prompts that are displayed to users who interact with a chatbot that uses this knowledge base. We recommend that you enable this setting.
+
If you activate conversation starters, "Automatic mode" is selected by default. "Manual mode" can be enabled only after you've added data sources to your knowledge base. link:manage-knowledgebase.html[Learn how to modify knowledge base settings].
.. *FSx for ONTAP file system*: When you define a new knowledge base, Workload factory creates a new Amazon FSx for NetApp ONTAP volume to store it. Choose an existing file system name and SVM (also called a storage VM) where the new volume will be created.
.. *Snapshot policy*: Choose a snapshot policy from the list of existing policies defined in the workload factory storage inventory. Recurring snapshots of the knowledge base will automatically be created at a frequency based on the snapshot policy you select.
+
If the snapshot policy you need doesn't exist, you can https://docs.netapp.com/us-en/ontap/data-protection/create-snapshot-policy-task.html[create a snapshot policy] on the storage VM that contains the volume.

. Select *Create knowledge base* to add the knowledge base to GenAI.
+
A progress indicator appears while the knowledge base is created.
+
After the knowledge base is created, you have the option to add a data source to your new knowledge base or to end the process without adding a data source. We recommend that you select *Add data source* and add one or more data sources now.

== Add data sources to the knowledge base

You can add one or more data sources to populate the knowledge base with your organization's data.

//NOTE: If you enabled data guardrails for the knowledge base, make sure you set the chunk size to #/between # and # so that Personal Identifiable Information (PII) can be found.
//add after Chen provides range

.About this task

The maximum number of supported data sources is 10.

.Steps

. After you select *Add data source*, the *Select a file system* page displays.

include::_include/add-data-source.adoc[]

.Result

The data source starts to be embedded into your knowledge base. The status changes from "Embedding" to "Embedded" when the data source is completely embedded.

After you add a single data source to the knowledge base, you can test it locally in the chatbot simulator window and make any required changes before you make the chatbot available to your users. You can also follow the same steps to add additional data sources to the knowledge base.