---
sidebar: sidebar
permalink: create-chatbot.html
keywords: ai, chatbot, creating
summary: After you have deployed the AI infrastructure and identified the data sources that you'll integrate in your chatbot, you are ready to build the chatbot using Workload Factory. As part of this step you'll also define the AI characteristics and create conversation starters.
---

= Create the chatbot
:icons: font
:imagesdir: ./media/

[.lead]
After you have deployed the AI infrastructure and identified the data sources that you'll integrate in your chatbot, you are ready to build the chatbot using Workload Factory. As part of this step you'll also define the AI characteristics and create conversation starters.

== Create the chatbot

You'll choose the data sources to integrate in your chatbot, and the Bedrock AI models that you want to use to create your chatbot.

.Steps

. Log in to Workload Factory.

. In the AI workloads tile, click *Deploy & manage*. 

. Click *Create chatbot* and then click *Add data source*.

. Select the FSx for ONTAP file system where your data source files reside and click *Next*.

. Select the volume on which your data source files reside and click *Next*.
+
When selecting files stored using the SMB protocol, enter the Active Directory information; including the Active Directory Domain, IP address, user name, and password. 

. Select the data source location based on where you have saved the files. This can be the entire volume or just a specific folder or sub-folder in the volume, and click *Next*.
+
The Define AI parameters page is displayed.

. In the Models section, define the models:

.. For Embedding model you can select only "Titan Embeddings G1" at this point.
+
https://aws.amazon.com/bedrock/titan/[Learn more about Amazon Titan^].
.. For Text model you can choose from a variety of AI models integrated in Amazon Bedrock. 
+
Learn more about the available models to help make your selection:
+
* https://aws.amazon.com/bedrock/claude/[Anthropic's Claude on Bedrock^]
* https://aws.amazon.com/bedrock/jurassic/[AI21 Labs Jurassic on Bedrock^]
* https://aws.amazon.com/bedrock/llama-2/[Meta Llama 2 on Bedrock^]
* https://aws.amazon.com/bedrock/cohere-command-embed/[Cohere Command on Bedrock^]

. In the Chunk definition section of the Define AI parameters page, define the chunks details:

.. For Chunking strategy you can choose "Sentences", "Words", or "Characters".
.. For Chunk size you can select only "256 Tokens" at this point.

. Click *Add* to add this data source.

.Result

The data source is embedded into your chatbot.

After you create the chatbot you'll be able to test it locally and make any required changes before you make the chatbot available to your users.
