---
sidebar: sidebar
permalink: create-chatbot.html
keywords: ai, chatbot, creating
summary: After you have deployed the AI infrastructure and identified the data sources that you'll integrate in your chatbot, you are ready to build the chatbot using Workload Factory. As part of this step you'll also define the AI characteristics and create conversation starters.
---

= Create the chatbot
:icons: font
:imagesdir: ./media/

[.lead]
After you have deployed the AI infrastructure and identified the data sources that you'll integrate in your chatbot, you are ready to build the chatbot using Workload Factory. As part of this step you'll also define the AI characteristics and create conversation starters.

After you create the chatbot you'll be able to test it locally and make any required changes before you make the chatbot available to your users.

== Create the chatbot

You'll choose the data sources to integrate in your chatbot, and the Bedrock AI models that you want to use to create your chatbot.

.Steps

. Log in to Workload Factory.

. In the AI workloads tile, click *Deploy & manage*. 

. Click *Create chatbot* and then click *Add data source*.

. Select the FSx for ONTAP file system where your data source files reside and click *Next*.

. Select the volume on which your data source files reside and click *Next*.
+
When selecting files stored using the SMB protocol, enter the Active Directory information; including the Active Directory Domain, IP address, user name, and password. 

. Select the data source location based on where you have saved the files. This can be the entire volume or just a specific folder or sub-folder in the volume, and click *Next*.
+
The Define AI parameters page is displayed.

. In the Models section, define the models:

.. For Embedding model you can select only "Titan Embeddings G1" at this point.
.. For Text model you can choose from a variety of Claude and Jurassic AI models. 
+
Learn mode about https://aws.amazon.com/bedrock/claude/[Claude on Bedrock^] and https://aws.amazon.com/bedrock/jurassic/[Jurassic on Bedrock^] to help make your selection.

. In the Chunk definition section of the Define AI parameters page, define the chunks details:

.. For Chunking strategy you can choose "Sentences", "Words", or "Characters".
.. For Chunk size you can select only "256 Tokens" at this point.

. Click *Add* to add this data source.

.Result

The data source is integrated into your chatbot.

== Test your chatbot

You can test your chatbot to make sure it performs as you expect, and you can customize the conversation starters that you want to be available by default for users of this chatbot. 

You'll perform most of your testing within Workload Factory before you deploy the chatbot in an application for your users. If you need to make changes to the chatbot operation, you'll want to do it now before it has been deployed.

Some of the tasks you'll want to perform to test your chatbot are:

* Enter a large number ot questions that are relevant to your organization to make sure the answers are as expected.
* Customize the conversation starters that you want to be available by default for your users.
* Make sure that the attributed content that is provided at the bottom of the chatbot answers contain the correct references. 

*More content here*
