---
sidebar: sidebar
permalink: create-application.html
keywords: ai, chatbot, creating, application, knowledgebase
summary: After you have built your knowledgebase and tested your chatbot, you are ready to set up the application that will enable your users to query the chatbot.
---

= Create the application to activate the chatbot
:icons: font
:imagesdir: ./media/

[.lead]
After you have built your knowledgebase and tested your chatbot, you are ready to set up the application that will enable your users to query the chatbot.

*Need Content for this topic*

Should this be called "Deploy your knowledgebase in an application"?


After you create the knowledgebase you'll be able to test the chatbot functionality locally and make any required changes before you make the chatbot available to your users.

== Deploy the chatbot

You'll choose the data sources to integrate in your chatbot, and the Bedrock AI models that you want to use to create your chatbot.

.Steps

. Log in to Workload Factory.

. In the AI workloads tile, click *Deploy & manage* and the Deploy chatbot infrastructure page is displayed.
+
This page 

. click *Create chatbot* and the xyz page is displayed

.Result

The data source are integrated into your chatbot.
