---
sidebar: sidebar
permalink: create-application.html
keywords: ai, chatbot, creating, application, knowledgebase
summary: After you have built your knowledgebase and tested your chatbot, you are ready to set up the application that will enable your users to query the chatbot.
---

= Create the application to activate the chatbot
:icons: font
:imagesdir: ./media/

[.lead]
After you have built your knowledgebase and tested your chatbot, you are ready to set up the application that will enable your users to query the chatbot.

To deploy a knowledgebase in your application, set it up to make https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_Retrieve.html[Retrieve] or https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_RetrieveAndGenerate.html[RetrieveAndGenerate] requests to the knowledge base. To see how to use these API operations, select the API tab in Test a knowledge base in Amazon Bedrock.


*Should this be called "Deploy your knowledgebase in an application"?*


== Deploy the chatbot

You'll choose the data sources to integrate in your chatbot, and the Bedrock AI models that you want to use to create your chatbot.

.Steps

. Log in to Workload Factory.

. In the AI workloads tile, click *Deploy & manage* and the Deploy chatbot infrastructure page is displayed.
+
This page 

. click *Create chatbot* and the xyz page is displayed

.Result

The data source are integrated into your chatbot.
