---
sidebar: sidebar
permalink: genai-engine-instance.html
keywords: genai engine, instance, ec2, role, iam role, permissions, security group, inbound, outbound, private endpoints
summary: When you deploy the GenAI infrastructure, workload factory creates an EC2 instance for the GenAI engine. It also creates an IAM role, security group, and private endpoints for this instance. You might want to understand more details about these components that workload factory creates in your AWS environment.
---

= Components for the NetApp GenAI engine
:icons: font
:imagesdir: ./media/

[.lead]
When you deploy the GenAI infrastructure, workload factory creates an EC2 instance for the GenAI engine. It also creates an IAM role, security group, and private endpoints for this instance. You might want to understand more details about these components that workload factory creates in your AWS environment.

EC2 instance type::
m5.large

IAM role::
The GenAI engine instance needs permissions to send chunks of data to the embedding model on Amazon Bedrock and to communicate with the NetApp AI Service Backend. Refer to the https://docs.netapp.com/us-en/workload-setup-admin/permissions-reference.html#permissions-for-genai-workloads[permissions reference^] for the permissions included in the IAM role.

Security group::
The outbound rules are open to all traffic, while the inbound rules are completely closed.

Private endpoints::
If the target VPC doesn't already have them, workload factory creates private endpoints for the GenAI engine EC2 instance so that it can communicate with the following AWS services:
+
* Amazon Bedrock
** bedrock
** bedrock-runtime
** bedrock-agent-runtime
* Amazon Elastic Container Registry (ECR)
** API
** docker
* AWS Systems Manager (SSM)
** ssm
** ec2messages
** ssmmessages
* Amazon FSx for NetApp ONTAP
* Amazon CloudWatch