---
sidebar: sidebar
permalink: identify-data-sources.html
keywords: data sources, chatbot, documents, knowledgebase
summary: Identify, or create, the documents (data sources) that reside on your FSx for ONTAP system that you'll integrate in your knowledgebase. These data sources enable the knowledgebase to provide accurate and personalized answers to user queries based on data that is relevant to your organization.
---

= Identify the data sources to integrate in your knowledgebase
:icons: font
:imagesdir: ./media/

[.lead]
Identify, or create, the documents (data sources) that reside on your FSx for ONTAP system that you'll integrate in your knowledgebase. These data sources enable the knowledgebase to provide accurate and personalized answers to user queries based on data that is relevant to your organization.

== Location of data sources

Data sources can be stored in a single volume, or in a folder within a volume, on an SMB share or NFS export on an Amazon FSx for NetApp ONTAP file system. You can't select individual documents within a volume or folder, therefore, you should ensure that each volume or folder that contains data sources does not contain extraneous documents that shouldn't be integrated with your chatbot.

You can add multiple data sources into each knowledgebase, but they all need to reside on FSx for ONTAP file systems that are accessible from your AWS account.

The maximum file size is 50 MB.

== Supported data source file formats

The following data source file formats are currently supported.

[cols=2*,options="header,autowidth"]
|===
| File format
| Extension

| Plain text | .txt
| Portable document | .pdf

|===
