---
sidebar: sidebar
permalink: identify-data-sources.html
keywords: data sources, chatbot, documents, knowledge base
summary: Identify, or create, the documents (data sources) that reside on your FSx for ONTAP file system that you'll integrate in your knowledge base. These data sources enable the knowledge base to provide accurate and personalized answers to user queries based on data that is relevant to your organization.
---

= Identify the data sources to integrate in your GenAI knowledge base
:icons: font
:imagesdir: ./media/

[.lead]
Identify, or create, the documents (data sources) that reside on your FSx for ONTAP file system that you'll integrate in your knowledge base. These data sources enable the knowledge base to provide accurate and personalized answers to user queries based on data that is relevant to your organization.

== Maximum number of data sources

The maximum number of supported data sources is 10.

== Location of data sources

Data sources can be stored in a single volume, or in a folder within a volume, on an SMB share or NFS export on an Amazon FSx for NetApp ONTAP file system. Data sources can also be stored on Amazon FSx for NetApp ONTAP volumes that are in a NetApp SnapMirror data protection relationship. 

You can't select individual documents within a volume or folder, therefore, you should ensure that each volume or folder that contains data sources does not contain extraneous documents that shouldn't be integrated with your knowledge base.

You can add multiple data sources into each knowledge base, but they all need to reside on FSx for ONTAP file systems that are accessible from your AWS account.

The maximum file size for each data source is 50 MB.

== Supported protocols

The knowledge base supports data from volumes that use either NFS or SMB/CIFS protocols. When selecting files stored using the SMB protocol, you'll need to enter the Active Directory information so that the knowledge base can access the files on those volumes. This includes the Active Directory Domain, IP address, user name, and password.

When storing your data source on a share (file or directory) accessed over SMB, the data is only accessible by chatbot users or groups who have the permissions to access that share. When this "permission-aware capability" is enabled, the AI system will compare the user email in auth0 to the users allowed to view or use the files on the SMB share. The chatbot will provide answers based on user permissions for the embedded files.

For example, if you have integrated 10 files (data sources) into your knowledge base, and 2 of the files are human resources files that contain restricted information, only chatbot users who are authenticated to access those 2 files will received responses from the chatbot that include data from those files.

== Supported data source file formats

The following data source file formats are currently supported.

[cols=2*,options="header,autowidth"]
|===
| File format
| Extension

| Apache Parquet | .parquet
| Comma-separated values file | .csv
| Graphics Interchange Format | .gif 
| JPEG | .jpg or.jpeg
| JSON and JSONP | .json
| Markdown | .md
| Microsoft Word | .doc or .docx
| Plain text | .txt
| Portable Document Format | .pdf
| Portable Network Graphics | .png
| WebP image | .webp
|===
