---
sidebar: sidebar
permalink: knowledgebase-prerequisites.html
keywords: ai, chatbot, prerequisites, bedrock, fsx for ontap, prerequisites
summary: You'll need to set up or verify many items before you can deploy a chatbot based on your knowledgebase. This includes having your AWS credentials to deploy the AWS infrastructure, an FSx for ONTAP file system, the list of data sources you want to integrate in your knowledgebase, access to the Amazon Bedrock AI service, and more.
---

= Verify knowledgebase and chatbot prerequisites
:icons: font
:imagesdir: ./media/

[.lead]
You'll need to set up or verify many items before you can deploy a chatbot based on your knowledgebase. This includes having your AWS credentials to deploy the AWS infrastructure, an FSx for ONTAP file system, the list of data sources you want to integrate in your knowledgebase, access to the Amazon Bedrock AI service, and more.
 
== Workload Factory requirements

* Account
* Credentials 

== AWS requirements

* AWS credentials
* AWS permissions and user 
* Amazon Bedrock service subscription
+
Amazon Bedrock enables you to use foundation models and it provides the capabilities to build generative AI applications. https://aws.amazon.com/bedrock/[Learn more about Amazon Bedrock].
* FSx for ONTAP file system
+
The system contains the data sources that you'll be integrating into your knowledgebase. It will also need to have enough free capacity so that the database that stores the data generated by the foundational model can be saved to a new volume.
+
You'll need to know the AWS region, VPC, and Subnet where the AWS FSx for ONTAP system resides.
* You'll need to know the tag key/value pairs that you want to apply to the AWS resources that are part of this deployment (optional).
* You'll need to know the Key pair that allows you to securely connect to the NetApp AI engine instance.
