settings:
  name: AI workloads
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar: 
  entries:
    - title: AI workloads docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /limitations.html
    - title: Get started
      entries:
        - title: Learn about Workload Factory for AI workloads
          url: /ai-workloads-overview.html
        - title: Getting started workflow
          url: /quick-start.html
        - title: Identify the documents to integrate in your chatbot
          url: /identify-data-sources.html
        - title: Create the chatbot
          url: /create-chatbot.html
        - title: What you can do next
          url: /whats-next.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family