settings:
  name: GenAI Studio
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar: 
  entries:
    - title: AI workloads docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /limitations.html
    - title: Get started
      entries:
        - title: Learn about Workload Factory for GenAI
          url: /ai-workloads-overview.html
        - title: Quick start
          url: /quick-start.html
    - title: FSx for ONTAP knowledge base requirements
      entries:
        - title: AWS requirements
          url: /aws-requirements.html
        - title: Workload Factory requirements
          url: /workload-factory-requirements.html    
    - title: Use AI workloads to create knowledge bases 
      entries:
        - title: Identify data sources for your knowledge base
          url: /identify-data-sources.html
        - title: Deploy the knowledge base infrastructure
          url: /deploy-infrastructure.html
        - title: Create the knowledge base
          url: /create-knowledgebase.html
        - title: Test the knowledge base
          url: /test-knowledgebase.html
        - title: Publish the knowledge base
          url: /publish-knowledgebase.html
        - title: Create a chatbot application to access your knowledge base
          url: /create-application.html
        - title: What you can do next
          url: /whats-next.html
    - title: Administer and monitor knowledge bases
      entries:
        - title: Manage data sources
          url: /manage-data-source.html
        - title: Manage knowledge bases
          url: /manage-knowledgebase.html
        - title: Manage knowledge base infrastructure
          url: /manage-infrastructure.html
        - title: Troubleshooting
          url: /troubleshooting.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html    
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family