settings:
  name: GenAI
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
  release_notes_autogen:
    release_notes_repo: workload-relnotes
sidebar: 
  entries:
    - title: GenAI docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
    - title: Learn about BlueXP workload factory for GenAI
      url: /general/ai-workloads-overview.html
      entries:
        - title: Components for the NetApp GenAI engine
          url: /general/genai-engine-instance.html 
    - title: Use GenAI to build knowledge bases for Amazon Bedrock
      entries:
        - title: Get started
          entries:
          - title: Quick start
            url: /quick-start-knowledge-base.html
          - title: Knowledge base requirements
            url: /requirements.html
          - title: Identify data sources to add to a knowledge base
            url: /identify-data-sources-knowledge-base.html
          - title: Deploy the GenAI infrastructure
            url: /deploy-infrastructure.html
        - title: Create a knowledge base
          url: /create-knowledgebase.html
        - title: Test a knowledge base
          url: /test-knowledgebase.html
        - title: Activate authentication
          url: /activate-authentication.html
        - title: Publish a knowledge base
          url: /publish-knowledgebase.html
        - title: Use the external example chatbot application
          url: /example-chatbot-application.html
        - title: Create a RAG-based AI application
          url: /create-application.html
        - title: What you can do next
          url: /whats-next.html
    - title: Use GenAI to create connectors for Amazon Q Business
      entries:
        - title: Get started
          entries:
          - title: Quick start
            url: /quick-start-connector.html
          - title: Knowledge base requirements
            url: /requirements-connector.html
          - title: Identify data sources to add to a knowledge base
            url: /identify-data-sources-connector.html
          - title: Deploy the GenAI infrastructure
            url: /deploy-infrastructure.html
        - title: Create an Amazon Q Business connector
          url: /define-connector.html   
    - title: Administer GenAI
      entries:
        - title: Manage the GenAI infrastructure
          url: /manage-infrastructure.html
        - title: Manage knowledge bases
          url: /manage-knowledgebase.html
        - title: Manage connectors
          url: /manage-connector.html
        - title: Manage data sources
          url: /manage-data-source.html  
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Troubleshooting
          url: /troubleshooting.html
        - title: Get help
          url: /get-help.html    
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP workload factory
  repo: workload-family