settings:
  name: AI workloads
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar: 
  entries:
    - title: AI workloads docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /limitations.html
    - title: Get started
      entries:
        - title: Learn about Workload Factory for AI workloads
          url: /ai-workloads-overview.html
        - title: Quick start
          url: /quick-start.html
        - title: Identify data sources for your knowledgebase
          url: /identify-data-sources.html
        - title: Deploy the knowledgebase infrastructure
          url: /deploy-infrastructure.html
        - title: Create the knowledgebase
          url: /create-knowledgebase.html
        - title: Test the knowledgebase
          url: /test-knowledgebase.html
        - title: Create the application to activate the chatbot
          url: /create-application.html
        - title: What you can do next
          url: /whats-next.html
    - title: Manage a knowledgebase
      entries:
        - title: Manage a data source
          url: /manage-data-source.html
        - title: Manage a knowledgebase
          url: /manage-knowledgebase.html
        - title: Manage knowledgebase infrastructure
          url: /manage-infrastructure.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /support-registration.html
        - title: Get help
          url: /get-help.html    
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: Workload Factory
  repo: workload-family