---
sidebar: sidebar
permalink: test-chatbot.html
keywords: ai, chatbot, creating
summary: After you create the chatbot you'll be able to test it locally and make any required changes before you make the chatbot available to your users.
---

= Test the chatbot
:icons: font
:imagesdir: ./media/

[.lead]
After you create the chatbot you'll be able to test it locally and make any required changes before you make the chatbot available to your users.

You test your chatbot to make sure it performs as you expect, and you can customize the conversation starters that you want to be available by default for users of this chatbot. 

You'll perform most of your testing within Workload Factory before you deploy the chatbot in an application for your users. If you need to make changes to the chatbot operation, you'll want to do it now before it has been deployed.

Some of the tasks you'll want to perform to test your chatbot are:

* Enter a large number ot questions that are relevant to your organization to make sure the answers are as expected.
* Customize the conversation starters that you want to be available by default for your users.
* Make sure that the attributed content that is provided at the bottom of the chatbot answers contain the correct references. 

*More content here*
