---
sidebar: sidebar
permalink: whats-next.html
keywords: what you can do, knowledge base
summary: Now that you've created a knowledge base using your enterprise data and deployed it for your users, you can manage the knowledge base, data sources, and the RAG infrastructure, including FSx for ONTAP file systems.
---

= What you can do next
:icons: font
:imagesdir: ./media/

[.lead]
Now that you've created a knowledge base using your enterprise data and deployed it for your users, you can manage the knowledge base, data sources, and the RAG infrastructure, including FSx for ONTAP file systems.

Some of the tasks you can perform to manage your knowledge base components are:

* Update the content of your data sources, or add new data sources, and sync those changes with your knowledge base and chatbot.
* Manage your data source settings, including the chunking strategy and permission awareness (for SMB file access). 
//and chunk size, 
* Manage your knowledge base settings, including the chat model and conversation starters.
* Unpublish a knowledge base or republish it after making changes.
* Back up and protect the important data on your FSx for ONTAP file system to make sure your knowledge base data and other infrastructure components are always available.

For information about managing your FSx for ONTAP file system, go to the https://docs.netapp.com/us-en/workload-fsx-ontap/index.html[workload factory for Amazon FSx for NetApp ONTAP documentation^] to view the backup and protection capabilities you can use.
