=== File type filtering for data sources
GenAI now supports selecting specific file types to include in the data source scan when you add a data source. 
 
link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base[Add data sources to the knowledge base]

=== File modification date filtering for data sources
GenAI now supports filtering files to include in the data source scan by modification date when you add a data source. You can choose a modification date range for the included files. 

link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base[Add data sources to the knowledge base]

=== Support for image files and enhanced support for PDF files 
GenAI now supports scanning image files and images within PDF files (also known as multi-modal file support). If you choose image files, the text from the images is scanned into the data source and used as data. This capability includes images within PDF documents; if you include PDF file types, images within each PDF are scanned for text, and that text is included in the information from the data source. 
 
link:https://docs.netapp.com/us-en/workload-genai/create-knowledgebase.html#add-data-sources-to-the-knowledge-base[Add data sources to the knowledge base]

=== Hybrid search and rerank support

GenAI can now enhance the relevance of search results by using hybrid search and re-ranking the results. Hybrid search combines keyword searches with vector and semantic searching. The standard keyword search results are augmented with close matches and linguistic nuance, enhancing relevance. GenAI can re-rank search results and only return results with the highest relevance. These features are available through Amazon AWS and are region-dependent. To use hybrid search and rerank features, you need to make sure you have enabled the correct AWS permissions.

link:#[New topic for permissions work]

